### PR TITLE
fix: according to documentation esp32 comes with 39 gpio pins. increa…

### PR DESCRIPTION
**Pull request by mistay**
…sed max gpio from 36 to 39 in order to add gpio37 to gpio39

### CODE REVIEW

**Comment by lukecyca** [comment]
Thanks!

**Comment by lukecyca** [comment]
Something failed when I tried to merge this PR. Now it shows the forked repository as `unknown repository`. @mistay did you delete your fork?

Regardless, I will make this change manually.

**Comment by mistay** [comment]
yes, sorry, deleted. but the fix is easy :)

**Comment by mistay** [comment]
just replace 36 by 39

**Pull request closed without merging**
